// ─── Portfolio TypeScript Types ───────────────────────────────────────────────

export type ProjectType = "photography" | "video" | "social-media";

export interface PortfolioCard {
  cardTitle: string;
  thumbnail: string;
  /** Optional explicit order override; if omitted, JSON array position is used */
  order?: number;
  /** 3–4 images cycled in the card preview slideshow */
  previewImages?: string[];
}

export interface BaseProject {
  slug: string;
  title: string;
  description: string;
  /** Heading displayed at the top of the project page (can include emoji) */
  heading: string;
  /** Full URL used for Open Graph social sharing image */
  ogImage: string;
  /** Set to false to hide from category listing and sitemap (default: true) */
  visible?: boolean;
  /** Card shown on the portfolio category index page */
  portfolioCard?: PortfolioCard;
}

export interface PhotographyProject extends BaseProject {
  type: "photography";
  /** Show download button on this project page */
  enableDownload: boolean;
  /** Number of images (used for structured data) */
  imageCount: number;
  /** Show the Slideshow hero above the gallery grid (default: true) */
  showSlideshow?: boolean;
}

export interface VideoItem {
  title: string;
  /** Full YouTube embed URL: https://www.youtube.com/embed/{ID} */
  embedUrl: string;
  /** ISO 8601 date string with timezone, e.g. "2023-01-01T00:00:00+08:00" */
  uploadDate: string;
}

export interface VideoProject extends BaseProject {
  type: "video";
  /** Longer intro paragraph shown above the video player */
  longDescription?: string;
  videos: VideoItem[];
}

export interface SocialMediaProject extends BaseProject {
  type: "social-media";
  /** Whether to show a gallery grid on this page */
  hasGallery: boolean;
  imageCount?: number;
  /** Whether to show a download button (unused; reserved for future use) */
  enableDownload?: boolean;
  /** Raw HTML string injected when hasGallery is false */
  customContent?: string;
}

export type AnyProject = PhotographyProject | VideoProject | SocialMediaProject;
/** Alias for AnyProject kept for readability in consuming files */
export type PortfolioProject = AnyProject;

// ─── Image manifest (generated by scripts/generate-manifests.js) ─────────────

export interface ImageManifestItem {
  basename: string;
  /** thumbnail WebP: basename-320.webp */
  thumb: string | null;
  /** medium WebP: basename-800.webp */
  md: string | null;
  /** large WebP: basename-1600.webp */
  lg: string | null;
  original: string | null;
}

// ─── Portfolio index page config ────────────────────────────────────────────

export interface InstagramLink {
  url: string;
  image: string;
  alt: string;
}

/** A single image entry for the homepage collage */
export interface CollageImageConfig {
  src: string;
  alt: string;
  srcFull: string;
  blur?: string;
  /** object-position for hero slideshow in cover mode, e.g. "center 30%" or "top" */
  objectPosition?: string;
}

export interface PortfolioIndexConfig {
  /** Images shown in the homepage gallery collage */
  collageImages: CollageImageConfig[];
  socialMediaLinks: InstagramLink[];
  videoSectionTitle: string;
  /**
   * How hero slideshow handles portrait / mixed images:
   * "cover" (default) | "blur" (blurred backdrop) | "white" (white backdrop)
   * Change in src/content/portfolio/index-config.json
   */
  heroFit?: "cover" | "blur" | "white";
}

// ─── Site-wide config (src/content/site.json) ────────────────────────────────

export interface SiteConfig {
  siteName: string;
  siteUrl: string;
  tagline: string;
  email: string;
  calendlyUrl: string;
  instagramUrl: string;
  linkedinUrl?: string;
  locations: string[];
  copyrightName: string;
}
